import x3dpsail


X3D0 = (x3dpsail.X3D().setProfile(x3dpsail.SFString("Immersive")).setVersion(x3dpsail.SFString("3.3"))
      .setHead(x3dpsail.head()
        .addMeta(x3dpsail.meta().setName(x3dpsail.SFString("title")).setContent(x3dpsail.SFString("abox.x3d")))
        .addMeta(x3dpsail.meta().setName(x3dpsail.SFString("creator")).setContent(x3dpsail.SFString("John Carlson")))
        .addMeta(x3dpsail.meta().setName(x3dpsail.SFString("generator")).setContent(x3dpsail.SFString("manual")))
        .addMeta(x3dpsail.meta().setName(x3dpsail.SFString("identifier")).setContent(x3dpsail.SFString("https://coderextreme.net/X3DJSONLD/abox.x3d")))
        .addMeta(x3dpsail.meta().setName(x3dpsail.SFString("description")).setContent(x3dpsail.SFString("a box"))))
      .setScene(x3dpsail.Scene()
        .addChild(x3dpsail.ProtoDeclare().setName(x3dpsail.SFString("anyShape"))
          .setProtoInterface(x3dpsail.ProtoInterface()
            .addField(x3dpsail.field().setName(x3dpsail.SFString("myShape")).setAccessType(x3dpsail.SFString("inputOutput")).setType(x3dpsail.SFString("MFNode"))
              .addChild(x3dpsail.Shape()
                .setGeometry(x3dpsail.Sphere()))))
          .setProtoBody(x3dpsail.ProtoBody()
            .addChild(x3dpsail.Transform()
              .setIS(x3dpsail.IS()
                .addConnect(x3dpsail.connect().setNodeField(x3dpsail.SFString("children")).setProtoField(x3dpsail.SFString("myShape")))))))
        .addChild(x3dpsail.ProtoDeclare().setName(x3dpsail.SFString("one"))
          .setProtoInterface(x3dpsail.ProtoInterface()
            .addField(x3dpsail.field().setName(x3dpsail.SFString("myShape")).setAccessType(x3dpsail.SFString("inputOutput")).setType(x3dpsail.SFString("MFNode"))
              .addChild(x3dpsail.Shape()
                .setGeometry(x3dpsail.Cylinder()))))
          .setProtoBody(x3dpsail.ProtoBody()
            .addChild(x3dpsail.Transform()
              .addChild(x3dpsail.ProtoInstance().setName(x3dpsail.SFString("anyShape"))
                .setIS(x3dpsail.IS()
                  .addConnect(x3dpsail.connect().setNodeField(x3dpsail.SFString("myShape")).setProtoField(x3dpsail.SFString("myShape"))))))))
        .addChild(x3dpsail.ProtoInstance().setName(x3dpsail.SFString("one"))
          .addFieldValue(x3dpsail.fieldValue().setName(x3dpsail.SFString("myShape"))
            .addChild(x3dpsail.Shape()
              .setGeometry(x3dpsail.Box().setSize(x3dpsail.SFVec3f(140,140,140))))))))

X3D0.toFileX3D("./future/./abox_RoundTrip.x3d")
