import jnius_config
jnius_config.set_classpath('.', 'X3DJSAIL.3.3.full.jar')
from jnius import autoclass
from X3Dautoclass import *
X3D0 = X3DObject() \
   .setProfile("Immersive") \
   .setVersion("3.3") \
   .setHead(headObject() \
    .addMeta(metaObject() \
     .setName("title") \
     .setContent("abox.x3d") \
    ) \
    .addMeta(metaObject() \
     .setName("creator") \
     .setContent("John Carlson") \
    ) \
    .addMeta(metaObject() \
     .setName("generator") \
     .setContent("manual") \
    ) \
    .addMeta(metaObject() \
     .setName("identifier") \
     .setContent("https://coderextreme.net/X3DJSONLD/abox.x3d") \
    ) \
    .addMeta(metaObject() \
     .setName("description") \
     .setContent("a box") \
    ) \
   ) \
   .setScene(SceneObject() \
    .addChildren(ProtoDeclareObject() \
     .setName("anyShape") \
     .setProtoInterface(ProtoInterfaceObject() \
      .addField(fieldObject() \
       .setName("myShape") \
       .setAccessType("inputOutput") \
       .setType("MFNode") \
       .addChildren(ShapeObject() \
        .setGeometry(SphereObject() \
        ) \
       ) \
      ) \
     ) \
     .setProtoBody(ProtoBodyObject() \
      .addChildren(TransformObject() \
       .setIS(ISObject() \
        .addConnect(connectObject() \
         .setNodeField("children") \
         .setProtoField("myShape") \
        ) \
       ) \
      ) \
     ) \
    ) \
    .addChildren(ProtoDeclareObject() \
     .setName("one") \
     .setProtoInterface(ProtoInterfaceObject() \
      .addField(fieldObject() \
       .setName("myShape") \
       .setAccessType("inputOutput") \
       .setType("MFNode") \
       .addChildren(ShapeObject() \
        .setGeometry(CylinderObject() \
        ) \
       ) \
      ) \
     ) \
     .setProtoBody(ProtoBodyObject() \
      .addChildren(TransformObject() \
       .addChildren(ProtoInstanceObject() \
        .setName("anyShape") \
        .setIS(ISObject() \
         .addConnect(connectObject() \
          .setNodeField("myShape") \
          .setProtoField("myShape") \
         ) \
        ) \
       ) \
      ) \
     ) \
    ) \
    .addChildren(ProtoInstanceObject() \
     .setName("one") \
     .addFieldValue(fieldValueObject() \
      .setName("myShape") \
      .addChildren(ShapeObject() \
       .setGeometry(BoxObject(size = [0.125,0.125,0.125]) \
       ) \
      ) \
     ) \
    ) \
   ) \

X3D0.toFileX3D("./future/./asmallbox.newf.x3d")
