import jnius_config
jnius_config.set_classpath('.', 'X3DJSAIL.3.3.full.jar')
from jnius import autoclass
from X3Dautoclass import *
X3D0 = X3DObject() \
   .setProfile("Immersive") \
   .setVersion("3.3") \
   .setHead(headObject() \
    .addMeta(metaObject() \
     .setName("title") \
     .setContent("box.x3d") \
    ) \
    .addMeta(metaObject() \
     .setName("creator") \
     .setContent("John Carlson") \
    ) \
    .addMeta(metaObject() \
     .setName("generator") \
     .setContent("manual") \
    ) \
    .addMeta(metaObject() \
     .setName("identifier") \
     .setContent("https://coderextreme.net/X3DJSONLD/box.x3d") \
    ) \
    .addMeta(metaObject() \
     .setName("description") \
     .setContent("3 boxes") \
    ) \
   ) \
   .setScene(SceneObject() \
    .addChild(NavigationInfoObject() \
     .setType(["EXAMINE"]) \
    ) \
    .addChild(ViewpointObject() \
     .setDescription("Cubes on Fire") \
     .setPosition([0,0,12]) \
    ) \
    .addChild(ProtoDeclareObject() \
     .setName("anyShape") \
     .setProtoInterface(ProtoInterfaceObject() \
      .addField(fieldObject() \
       .setType(fieldObject.TYPE_SFVEC3F) \
       .setName("xtranslation") \
       .setAccessType(fieldObject.ACCESSTYPE_INPUTOUTPUT) \
       .setValue("0 0 0") \
      ) \
      .addField(fieldObject() \
       .setType(fieldObject.TYPE_MFNODE) \
       .setName("myShape") \
       .setAccessType(fieldObject.ACCESSTYPE_INPUTOUTPUT) \
       .addChild(ShapeObject() \
        .setGeometry(SphereObject() \
        ) \
        .setAppearance(AppearanceObject() \
         .setMaterial(MaterialObject() \
          .setDiffuseColor([1,1,1]) \
         ) \
        ) \
       ) \
      ) \
     ) \
     .setProtoBody(ProtoBodyObject() \
      .addChild(TransformObject() \
       .setIS(ISObject() \
        .addConnect(connectObject() \
         .setNodeField("translation") \
         .setProtoField("xtranslation") \
        ) \
        .addConnect(connectObject() \
         .setNodeField("children") \
         .setProtoField("myShape") \
        ) \
       ) \
      ) \
     ) \
    ) \
    .addChild(ProtoDeclareObject() \
     .setName("three") \
     .setProtoInterface(ProtoInterfaceObject() \
      .addField(fieldObject() \
       .setType(fieldObject.TYPE_SFVEC3F) \
       .setName("ytranslation") \
       .setAccessType(fieldObject.ACCESSTYPE_INPUTOUTPUT) \
       .setValue("0 0 0") \
      ) \
      .addField(fieldObject() \
       .setType(fieldObject.TYPE_MFNODE) \
       .setName("myShape") \
       .setAccessType(fieldObject.ACCESSTYPE_INPUTOUTPUT) \
       .addChild(ShapeObject() \
        .setGeometry(CylinderObject() \
        ) \
        .setAppearance(AppearanceObject() \
         .setMaterial(MaterialObject() \
          .setDiffuseColor([1,1,1]) \
         ) \
        ) \
       ) \
      ) \
     ) \
     .setProtoBody(ProtoBodyObject() \
      .addChild(TransformObject() \
       .setIS(ISObject() \
        .addConnect(connectObject() \
         .setNodeField("translation") \
         .setProtoField("ytranslation") \
        ) \
       ) \
       .addChild(ProtoInstanceObject() \
        .setName("anyShape") \
        .addFieldValue(fieldValueObject() \
         .setName("xtranslation") \
         .setValue("0 0 0") \
        ) \
        .setIS(ISObject() \
         .addConnect(connectObject() \
          .setNodeField("myShape") \
          .setProtoField("myShape") \
         ) \
        ) \
       ) \
       .addChild(ProtoInstanceObject() \
        .setName("anyShape") \
        .addFieldValue(fieldValueObject() \
         .setName("xtranslation") \
         .setValue("2 0 0") \
        ) \
        .setIS(ISObject() \
         .addConnect(connectObject() \
          .setNodeField("myShape") \
          .setProtoField("myShape") \
         ) \
        ) \
       ) \
       .addChild(ProtoInstanceObject() \
        .setName("anyShape") \
        .addFieldValue(fieldValueObject() \
         .setName("xtranslation") \
         .setValue("-2 0 0") \
        ) \
        .setIS(ISObject() \
         .addConnect(connectObject() \
          .setNodeField("myShape") \
          .setProtoField("myShape") \
         ) \
        ) \
       ) \
      ) \
     ) \
    ) \
    .addChild(ProtoInstanceObject() \
     .setName("three") \
     .addFieldValue(fieldValueObject() \
      .setName("ytranslation") \
      .setValue("0 0 0") \
     ) \
     .addFieldValue(fieldValueObject() \
      .setName("myShape") \
      .addChild(ShapeObject() \
       .setGeometry(BoxObject() \
        .setSize([1,1,1]) \
       ) \
       .setAppearance(AppearanceObject() \
        .setMaterial(MaterialObject() \
         .setDiffuseColor([0,1,0]) \
        ) \
       ) \
      ) \
     ) \
    ) \
   ) \

X3D0.toFileX3D("./future/./Box.newf.x3d")
