import jnius_config
jnius_config.set_classpath('.', 'X3DJSAIL.3.3.full.jar')
from jnius import autoclass
from X3Dautoclass import *
X3D0 = X3DObject() \
   .setProfile("Immersive") \
   .setVersion("3.3") \
   .setHead(headObject() \
    .addMeta(metaObject() \
     .setName("title") \
     .setContent("CoordinateAxis.x3d") \
    ) \
    .addMeta(metaObject() \
     .setName("creator") \
     .setContent("Unknown, see X3D Resources Archives") \
    ) \
    .addMeta(metaObject() \
     .setName("generator") \
     .setContent("manual") \
    ) \
    .addMeta(metaObject() \
     .setName("identifier") \
     .setContent("https://coderextreme.net/X3DJSONLD/CoordinateAxis.x3d") \
    ) \
    .addMeta(metaObject() \
     .setName("description") \
     .setContent("a box") \
    ) \
   ) \
   .setScene(SceneObject() \
    .addChild(CollisionObject() \
     .setDEF("DoNotCollideWithVisualizationWidget") \
     .addComments(CommentsBlock("""Invoke CoordinateAxes in other scenes as an Inline child inside a scaling Transform node, at the topmost level of the scene graph.""")) \
     .addComments(CommentsBlock("""This NavigationInfo allows examine mode and will be overridden by any parent scene.""")) \
     .addComments(CommentsBlock("""Each arrow goes from +1m to -1m to allow linear scaling to fit a scene""")) \
     .addComments(CommentsBlock("""Note each label rotates about the scene's vertical Y axis for consistency, enabling local orientation by user""")) \
     .addChild(GroupObject() \
      .addComments(CommentsBlock("""Vertical Y arrow and label""")) \
      .addChild(GroupObject() \
       .setDEF("ArrowGreen") \
       .addChild(ShapeObject() \
        .setGeometry(CylinderObject() \
         .setDEF("ArrowCylinder") \
         .setRadius(0.025) \
         .setTop(False) \
        ) \
        .setAppearance(AppearanceObject() \
         .setDEF("Green") \
         .setMaterial(MaterialObject() \
          .setDiffuseColor([0.1,0.6,0.1]) \
          .setEmissiveColor([0.05,0.2,0.05]) \
         ) \
        ) \
       ) \
       .addChild(TransformObject() \
        .setTranslation([0,1,0]) \
        .addChild(ShapeObject() \
         .setGeometry(ConeObject() \
          .setDEF("ArrowCone") \
          .setBottomRadius(0.05) \
          .setHeight(0.1) \
         ) \
         .setAppearance(AppearanceObject() \
          .setUSE("Green") \
         ) \
        ) \
       ) \
      ) \
      .addChild(TransformObject() \
       .setTranslation([0,1.08,0]) \
       .addChild(BillboardObject() \
        .addChild(ShapeObject() \
         .setAppearance(AppearanceObject() \
          .setDEF("LABEL_APPEARANCE") \
          .setMaterial(MaterialObject() \
           .setDiffuseColor([1,1,0.3]) \
           .setEmissiveColor([0.33,0.33,0.1]) \
          ) \
         ) \
         .setGeometry(TextObject() \
          .setString(["Y"]) \
          .setFontStyle(FontStyleObject() \
           .setDEF("LABEL_FONT") \
           .setFamily(["SANS"]) \
           .setJustify(["MIDDLE","MIDDLE"]) \
           .setSize(0.2) \
          ) \
         ) \
        ) \
       ) \
      ) \
     ) \
     .addChild(TransformObject() \
      .setRotation([0,0,1,-1.57079]) \
      .addComments(CommentsBlock("""Horizontal X arrow and label""")) \
      .addChild(GroupObject() \
       .addChild(GroupObject() \
        .setDEF("ArrowRed") \
        .addChild(ShapeObject() \
         .setGeometry(CylinderObject() \
          .setUSE("ArrowCylinder") \
         ) \
         .setAppearance(AppearanceObject() \
          .setDEF("Red") \
          .setMaterial(MaterialObject() \
           .setDiffuseColor([0.7,0.1,0.1]) \
           .setEmissiveColor([0.33,0,0]) \
          ) \
         ) \
        ) \
        .addChild(TransformObject() \
         .setTranslation([0,1,0]) \
         .addChild(ShapeObject() \
          .setGeometry(ConeObject() \
           .setUSE("ArrowCone") \
          ) \
          .setAppearance(AppearanceObject() \
           .setUSE("Red") \
          ) \
         ) \
        ) \
       ) \
       .addChild(TransformObject() \
        .setRotation([0,0,1,1.57079]) \
        .setTranslation([0.072,1.1,0]) \
        .addComments(CommentsBlock("""note label rotated back to original coordinate frame""")) \
        .addChild(BillboardObject() \
         .addChild(ShapeObject() \
          .setAppearance(AppearanceObject() \
           .setUSE("LABEL_APPEARANCE") \
          ) \
          .setGeometry(TextObject() \
           .setString(["X"]) \
           .setFontStyle(FontStyleObject() \
            .setUSE("LABEL_FONT") \
           ) \
          ) \
         ) \
        ) \
       ) \
      ) \
     ) \
     .addChild(TransformObject() \
      .setRotation([1,0,0,1.57079]) \
      .addComments(CommentsBlock("""Perpendicular Z arrow and label, note right-hand rule""")) \
      .addChild(GroupObject() \
       .addChild(GroupObject() \
        .setDEF("ArrowBlue") \
        .addChild(ShapeObject() \
         .setGeometry(CylinderObject() \
          .setUSE("ArrowCylinder") \
         ) \
         .setAppearance(AppearanceObject() \
          .setDEF("Blue") \
          .setMaterial(MaterialObject() \
           .setDiffuseColor([0.3,0.3,1]) \
           .setEmissiveColor([0.1,0.1,0.33]) \
          ) \
         ) \
        ) \
        .addChild(TransformObject() \
         .setTranslation([0,1,0]) \
         .addChild(ShapeObject() \
          .setGeometry(ConeObject() \
           .setUSE("ArrowCone") \
          ) \
          .setAppearance(AppearanceObject() \
           .setUSE("Blue") \
          ) \
         ) \
        ) \
       ) \
       .addChild(TransformObject() \
        .setRotation([1,0,0,-1.57079]) \
        .setTranslation([0,1.1,0.072]) \
        .addComments(CommentsBlock("""note label rotated back to original coordinate frame""")) \
        .addChild(BillboardObject() \
         .addChild(ShapeObject() \
          .setAppearance(AppearanceObject() \
           .setUSE("LABEL_APPEARANCE") \
          ) \
          .setGeometry(TextObject() \
           .setString(["Z"]) \
           .setFontStyle(FontStyleObject() \
            .setUSE("LABEL_FONT") \
           ) \
          ) \
         ) \
        ) \
       ) \
      ) \
     ) \
    ) \
   ) \

X3D0.toFileX3D("./future/./CoordinateAxes.newf.x3d")
