import jnius_config
jnius_config.set_classpath('.', 'X3DJSAIL.3.3.full.jar')
from jnius import autoclass
from X3Dautoclass import *
X3D0 = X3DObject() \
   .setProfile("Immersive") \
   .setVersion("3.3") \
   .setHead(headObject() \
    .addMeta(metaObject() \
     .setName("title") \
     .setContent("ObliqueStrategies.x3d") \
    ) \
    .addMeta(metaObject() \
     .setName("description") \
     .setContent("Text scripting and animation example using Oblique Strategies card set by Brian Eno.") \
    ) \
    .addMeta(metaObject() \
     .setName("creator") \
     .setContent("Don Brutzman, John Kelly, Ben Cheng") \
    ) \
    .addMeta(metaObject() \
     .setName("created") \
     .setContent("3 November 2013") \
    ) \
    .addMeta(metaObject() \
     .setName("modified") \
     .setContent("18 October 2015") \
    ) \
    .addMeta(metaObject() \
     .setName("reference") \
     .setContent("oblique.html") \
    ) \
    .addMeta(metaObject() \
     .setName("reference") \
     .setContent("ObliqueStrategies.txt") \
    ) \
    .addMeta(metaObject() \
     .setName("reference") \
     .setContent("ObliqueStrategiesScript.js") \
    ) \
    .addMeta(metaObject() \
     .setName("reference") \
     .setContent("http://music.hyperreal.org/artists/brian_eno/oblique/oblique.html") \
    ) \
    .addMeta(metaObject() \
     .setName("reference") \
     .setContent("http://www.eno-web.co.uk/obliques.html") \
    ) \
    .addMeta(metaObject() \
     .setName("reference") \
     .setContent("http://gothpunk.com/haiku-intro.html") \
    ) \
    .addMeta(metaObject() \
     .setName("reference") \
     .setContent("http://www.rtqe.net/ObliqueStrategies/OSintro.html") \
    ) \
    .addMeta(metaObject() \
     .setName("reference") \
     .setContent("https://en.wikipedia.org/wiki/Oblique_Strategies") \
    ) \
    .addMeta(metaObject() \
     .setName("subject") \
     .setContent("Brian Eno, Oblique Strategies") \
    ) \
    .addMeta(metaObject() \
     .setName("Image") \
     .setContent("images/ObliqueStrategiesEntryScreen.png") \
    ) \
    .addMeta(metaObject() \
     .setName("audio") \
     .setContent("http://translate.google.com/translate_tts?tl=en&q=hello%20X3D") \
    ) \
    .addMeta(metaObject() \
     .setName("audio") \
     .setContent("translate_tts_HelloX3D.mp3") \
    ) \
    .addMeta(metaObject() \
     .setName("audio") \
     .setContent("translate_tts_HelloX3D.wav") \
    ) \
    .addMeta(metaObject() \
     .setName("TODO") \
     .setContent("multiliingual translation parameter") \
    ) \
    .addMeta(metaObject() \
     .setName("reference") \
     .setContent("http://stackoverflow.com/questions/9163988/download-mp3-from-google-translate-text-to-speech") \
    ) \
    .addMeta(metaObject() \
     .setName("reference") \
     .setContent("http://www.greenbot.com/article/2105862/how-to-get-started-with-google-text-to-speech.html") \
    ) \
    .addMeta(metaObject() \
     .setName("warning") \
     .setContent("under development, scene Sound/AudioClip triggering (or retrieved file format) not working") \
    ) \
    .addMeta(metaObject() \
     .setName("warning") \
     .setContent("BSContact error: Script node TextScript: parse error: line 15 \" var strategy = [];") \
    ) \
    .addMeta(metaObject() \
     .setName("identifier") \
     .setContent("http://X3dGraphics.com/examples/X3dForAdvancedModeling/Inspiration/ObliqueStrategies.x3d") \
    ) \
    .addMeta(metaObject() \
     .setName("generator") \
     .setContent("X3D-Edit 3.3, https://savage.nps.edu/X3D-Edit") \
    ) \
    .addMeta(metaObject() \
     .setName("license") \
     .setContent("../license.html") \
    ) \
   ) \
   .setScene(SceneObject() \
    .addChildren(NavigationInfoObject() \
    ) \
    .addChildren(BackgroundObject() \
     .setSkyColor([0.419608,0.427451,1]) \
    ) \
    .addChildren(TransformObject() \
     .setScale([0.4,0.4,0.4]) \
     .setTranslation([0,1,0]) \
     .addChildren(TouchSensorObject() \
      .setDEF("RandomTextClickedSensor") \
      .setDescription("Select to see a new strategy") \
     ) \
     .addChildren(ShapeObject() \
      .setGeometry(TextObject() \
       .setString(["Oblique Strategies","","(Over One Hundred Worthwhile Dilemmas)","","by Brian Eno and Peter Schmidt"]) \
       .setFontStyle(FontStyleObject(family = ["SANS"], justify = ["MIDDLE","MIDDLE"], style = "BOLD") \
        .setDEF("MessageFont") \
       ) \
      ) \
      .setAppearance(AppearanceObject() \
       .setMaterial(MaterialObject() \
        .setDiffuseColor([1,1,1]) \
       ) \
      ) \
     ) \
     .addChildren(TransformObject() \
      .setScale([10,3,1]) \
      .addChildren(ShapeObject() \
       .setDEF("HeadlineClickSurface") \
       .setGeometry(IndexedFaceSetObject(coordIndex = [0,1,2,3,-1], solid = False) \
        .setCoord(CoordinateObject() \
         .setPoint([1,1,0,1,-1,0,-1,-1,0,-1,1,0]) \
        ) \
       ) \
       .setAppearance(AppearanceObject() \
        .setMaterial(MaterialObject() \
         .setAmbientIntensity(0.245763) \
         .setDiffuseColor([0.34773,0.090909,0.005289]) \
         .setShininess(0.07) \
         .setSpecularColor([0.336735,0.051091,0.051091]) \
         .setTransparency(0.8) \
        ) \
       ) \
      ) \
     ) \
    ) \
    .addChildren(ScriptObject() \
     .setDEF("TextScript") \
     .setUrl(["./ObliqueStrategiesScript.js"]) \
#initialize() method includes unit test to printAllStrategies() to console
#TODO insert field definitions here (index string_changed previous next random) and then animate!
     .addField(fieldObject() \
      .setName("index") \
      .setAccessType("initializeOnly") \
      .setAppinfo("index for active strategy card, -1 means no selection") \
      .setType("SFInt32") \
      .setValue("0") \
     ) \
     .addField(fieldObject() \
      .setName("string_changed") \
      .setAccessType("outputOnly") \
      .setAppinfo("latest strategy card value") \
      .setType("MFString") \
     ) \
     .addField(fieldObject() \
      .setName("textToSpeechUrl") \
      .setAccessType("outputOnly") \
      .setAppinfo("url to invoke Google Translate") \
      .setType("MFString") \
     ) \
     .addField(fieldObject() \
      .setName("newCardTime") \
      .setAccessType("outputOnly") \
      .setAppinfo("activate Sound node") \
      .setType("SFTime") \
     ) \
     .addField(fieldObject() \
      .setName("selectPreviousCard") \
      .setAccessType("inputOnly") \
      .setType("SFBool") \
     ) \
     .addField(fieldObject() \
      .setName("selectNextCard") \
      .setAccessType("inputOnly") \
      .setType("SFBool") \
     ) \
     .addField(fieldObject() \
      .setName("selectRandomCard") \
      .setAccessType("inputOnly") \
      .setType("SFBool") \
     ) \
     .addField(fieldObject() \
      .setName("traceEnabled") \
      .setAccessType("initializeOnly") \
      .setAppinfo("controls console tracing") \
      .setType("SFBool") \
      .setValue("true") \
     ) \
    ) \
    .addChildren(TransformObject() \
     .setDEF("CardTransform") \
     .setScale([0.4,0.4,0.4]) \
     .setTranslation([0,-1.5,0]) \
     .addChildren(ShapeObject() \
      .setGeometry(TextObject() \
       .setDEF("CardText") \
       .setFontStyle(FontStyleObject(family = ["SANS"], justify = ["MIDDLE","MIDDLE"], style = "BOLD") \
       ) \
      ) \
      .setAppearance(AppearanceObject() \
       .setMaterial(MaterialObject() \
        .setDiffuseColor([1,1,1]) \
       ) \
      ) \
     ) \
     .addChildren(ROUTEObject() \
      .setFromField("string_changed") \
      .setFromNode("TextScript") \
      .setToField("string") \
      .setToNode("CardText") \
     ) \
     .addChildren(SoundObject() \
      .setDEF("CardSoundSpatialization") \
      .setMaxBack(100) \
      .setMaxFront(100) \
      .setMinBack(20) \
      .setMinFront(20) \
#Make sure the sound source AudioClip is audible at the user location
#Not all X3D players seem to use the .mp3
#&#38; is ampersand character, avoids escaping problems and inconsistencies in browsers and X3D players
#%20 is space character used in uri/url encoding
      .setSource(AudioClipObject() \
       .setDEF("TextToSpeechAudioClip") \
       .setDescription("sends strategy text google translate") \
       .setUrl(["http://translate.google.com/translate_tts?tl=en&q=Feed%20the%20recording%20back%20out%20of%20the%20medium","translate_tts_mp3FileFormatNotSupported.wav"]) \
      ) \
     ) \
     .addChildren(ROUTEObject() \
      .setFromField("textToSpeechUrl") \
      .setFromNode("TextScript") \
      .setToField("url") \
      .setToNode("TextToSpeechAudioClip") \
     ) \
     .addChildren(ROUTEObject() \
      .setFromField("newCardTime") \
      .setFromNode("TextScript") \
      .setToField("startTime") \
      .setToNode("TextToSpeechAudioClip") \
     ) \
    ) \
    .addChildren(TransformObject() \
     .setScale([0.4,0.4,0.4]) \
     .setTranslation([-3.2,2.5,0]) \
     .addChildren(TouchSensorObject() \
      .setDEF("PreviousTextClickedSensor") \
      .setDescription("Select to see previous strategy") \
     ) \
     .addChildren(ROUTEObject() \
      .setFromField("isActive") \
      .setFromNode("PreviousTextClickedSensor") \
      .setToField("selectPreviousCard") \
      .setToNode("TextScript") \
     ) \
     .addChildren(ShapeObject() \
      .setGeometry(TextObject() \
       .setString(["previous"]) \
       .setFontStyle(FontStyleObject() \
        .setUSE("MessageFont") \
       ) \
      ) \
      .setAppearance(AppearanceObject() \
       .setDEF("InterfaceAppearance") \
       .setMaterial(MaterialObject() \
        .setDiffuseColor([1,0,0.6]) \
       ) \
      ) \
     ) \
     .addChildren(TransformObject() \
      .setScale([2,0.6,1]) \
      .addChildren(ShapeObject() \
       .setDEF("TransparentClickSurface") \
#support Selectable Text with a scalable IFS
       .setGeometry(IndexedFaceSetObject(coordIndex = [0,1,2,3,-1], solid = False) \
        .setCoord(CoordinateObject() \
         .setPoint([1,1,0,1,-1,0,-1,-1,0,-1,1,0]) \
        ) \
       ) \
       .setAppearance(AppearanceObject() \
        .setMaterial(MaterialObject() \
         .setTransparency(1) \
        ) \
       ) \
      ) \
     ) \
    ) \
    .addChildren(TransformObject() \
     .setScale([0.4,0.4,0.4]) \
     .setTranslation([3.5,2.5,0]) \
     .addChildren(TouchSensorObject() \
      .setDEF("NextTextClickedSensor") \
      .setDescription("Select to see next strategy") \
     ) \
     .addChildren(ROUTEObject() \
      .setFromField("isActive") \
      .setFromNode("NextTextClickedSensor") \
      .setToField("selectNextCard") \
      .setToNode("TextScript") \
     ) \
     .addChildren(ShapeObject() \
      .setGeometry(TextObject() \
       .setString(["next"]) \
       .setFontStyle(FontStyleObject() \
        .setUSE("MessageFont") \
       ) \
      ) \
      .setAppearance(AppearanceObject() \
       .setUSE("InterfaceAppearance") \
      ) \
     ) \
     .addChildren(TransformObject() \
      .setScale([1.2,0.6,1]) \
      .addChildren(ShapeObject() \
       .setUSE("TransparentClickSurface") \
      ) \
     ) \
    ) \
    .addChildren(TransformObject() \
     .setScale([0.4,0.4,0.4]) \
     .setTranslation([-3.3,-0.5,0]) \
     .addChildren(TouchSensorObject() \
      .setUSE("RandomTextClickedSensor") \
     ) \
     .addChildren(ROUTEObject() \
      .setFromField("isActive") \
      .setFromNode("RandomTextClickedSensor") \
      .setToField("selectRandomCard") \
      .setToNode("TextScript") \
     ) \
     .addChildren(ShapeObject() \
      .setGeometry(TextObject() \
       .setString(["random"]) \
       .setFontStyle(FontStyleObject() \
        .setUSE("MessageFont") \
       ) \
      ) \
      .setAppearance(AppearanceObject() \
       .setUSE("InterfaceAppearance") \
      ) \
     ) \
     .addChildren(TransformObject() \
      .setScale([1.8,0.6,1]) \
      .addChildren(ShapeObject() \
       .setUSE("TransparentClickSurface") \
      ) \
     ) \
    ) \
    .addChildren(TransformObject() \
     .setScale([0.4,0.4,0.4]) \
     .setTranslation([3.3,-0.5,0]) \
     .addChildren(AnchorObject() \
      .setDEF("TextToSpeechAnchor") \
      .setDescription("text to speech in browser") \
      .setParameter(["target=_blank"]) \
      .setUrl(["http://translate.google.com/translate_tts?tl=en&q=Overtly%20resist%20change"]) \
      .addChildren(ROUTEObject() \
       .setFromField("textToSpeechUrl") \
       .setFromNode("TextScript") \
       .setToField("url") \
       .setToNode("TextToSpeechAnchor") \
      ) \
      .addChildren(ShapeObject() \
       .setGeometry(TextObject() \
        .setString(["speech"]) \
        .setFontStyle(FontStyleObject() \
         .setUSE("MessageFont") \
        ) \
       ) \
       .setAppearance(AppearanceObject() \
        .setUSE("InterfaceAppearance") \
       ) \
      ) \
      .addChildren(TransformObject() \
       .setScale([1.8,0.6,1]) \
       .addChildren(ShapeObject() \
        .setUSE("TransparentClickSurface") \
       ) \
      ) \
     ) \
    ) \
   ) \

X3D0.toFileX3D("./future/./ObliqueStrategies.newf.x3d")
