@ECHO OFF
set PYSAIHOME=.
set X3DJSONLD=..\X3DJSONLD
set PYTHONPATH=C:\Python27;c:\Python27\Scripts
set PATH=C:\Windows;%PYTHONPATH%;%JDK_HOME%\bin:%PATH%
set CLASSPATH=.;%PYSAIHOME%\saxon-he-12.1.jar;%PYSAIHOME%\X3DJSAIL.4.0.classes.jar
set PYTHON=py.exe
set PIP=pip.exe
set NODE=node.exe
@ECHO ON
