@ECHO OFF
set PYSAIHOME=.
set X3DJSONLD=..\X3DJSONLD
set PYTHONPATH=C:\Python27;c:\Python27\Scripts
set PATH=%PYTHONPATH%;%JDK_HOME%\bin:%JDK_HOME%\jre\lib\amd64\server:%PATH%
set CLASSPATH=%PYSAIHOME%\saxon9he.jar;%PYSAIHOME%\X3DJSAIL.3.3.classes.jar
set PYTHON=python.exe
set PIP=pip.exe
set NODE=node.exe
