import x3dpsail


X3D0 = (x3dpsail.X3D().setProfile(x3dpsail.SFString("Immersive")).setVersion(x3dpsail.SFString("3.0"))
      .setHead(x3dpsail.head()
        .addMeta(x3dpsail.meta().setName(x3dpsail.SFString("title")).setContent(x3dpsail.SFString("TextExamples.x3d")))
        .addMeta(x3dpsail.meta().setName(x3dpsail.SFString("description")).setContent(x3dpsail.SFString("Show different escape-character text examples for embedded quotation marks.")))
        .addMeta(x3dpsail.meta().setName(x3dpsail.SFString("creator")).setContent(x3dpsail.SFString("Don Brutzman")))
        .addMeta(x3dpsail.meta().setName(x3dpsail.SFString("created")).setContent(x3dpsail.SFString("7 April 2001")))
        .addMeta(x3dpsail.meta().setName(x3dpsail.SFString("modified")).setContent(x3dpsail.SFString("26 April 2016")))
        .addMeta(x3dpsail.meta().setName(x3dpsail.SFString("warning")).setContent(x3dpsail.SFString("Note that X3D Canonicalization (C14N) will scrub alternate XML character representations, be careful to check original encoding into version control.")))
        .addMeta(x3dpsail.meta().setName(x3dpsail.SFString("warning")).setContent(x3dpsail.SFString("Usually this source document needs to be inspected and edited using a plain-text editor in order to see the differences in these XML-equivalent text representations.")))
        .addMeta(x3dpsail.meta().setName(x3dpsail.SFString("identifier")).setContent(x3dpsail.SFString("http://www.web3d.org/x3d/content/examples/Basic/development/TextExamples.x3d")))
        .addMeta(x3dpsail.meta().setName(x3dpsail.SFString("generator")).setContent(x3dpsail.SFString("X3D-Edit 3.3, https://savage.nps.edu/X3D-Edit")))
        .addMeta(x3dpsail.meta().setName(x3dpsail.SFString("license")).setContent(x3dpsail.SFString("../license.html"))))
      .setScene(x3dpsail.Scene()
        .addChild(x3dpsail.Transform().setTranslation(x3dpsail.SFVec3f(0,2,0))
          .addChild(x3dpsail.Shape()
            .setGeometry(x3dpsail.Text().setString(x3dpsail.MFString(["Compare special character escaping"]))
              .setFontStyle(x3dpsail.FontStyle().setDEF(x3dpsail.SFString("testFontStyle")).setJustify(x3dpsail.MFString(["MIDDLE","MIDDLE"])).setSize(x3dpsail.SFFloat(0.8))))
            .setAppearance(x3dpsail.Appearance().setDEF(x3dpsail.SFString("LightBlueAppearance"))
              .setMaterial(x3dpsail.Material().setDiffuseColor(x3dpsail.SFColor(0.1,0.7,0.7))))))
        .addChild(x3dpsail.Transform().setTranslation(x3dpsail.SFVec3f(-3,0,0))
          .addChild(x3dpsail.Shape()
            .setGeometry(x3dpsail.Text().setString(x3dpsail.MFString(["I don't think so","","he said \"Hi\""]))
              .setFontStyle(x3dpsail.FontStyle().setUSE(x3dpsail.SFString("testFontStyle"))))
            .setAppearance(x3dpsail.Appearance().setUSE(x3dpsail.SFString("LightBlueAppearance")))))
        .addChild(x3dpsail.Transform().setTranslation(x3dpsail.SFVec3f(3,0,0))
          .addChild(x3dpsail.Shape()
            .setGeometry(x3dpsail.Text().setString(x3dpsail.MFString(["I don't think so","","he said \"Hi\""]))
              .setFontStyle(x3dpsail.FontStyle().setUSE(x3dpsail.SFString("testFontStyle"))))
            .setAppearance(x3dpsail.Appearance().setUSE(x3dpsail.SFString("LightBlueAppearance")))))))

X3D0.toFileX3D("./future/./TextExamples_RoundTrip.x3d")
