import jnius_config
jnius_config.set_classpath('.', 'X3DJSAIL.3.3.full.jar')
from jnius import autoclass
from X3Dautoclass import *
X3D0 = X3DObject() \
   .setProfile("Immersive") \
   .setVersion("3.3") \
   .setHead(headObject() \
    .addComponent(componentObject() \
     .setName("Geospatial") \
     .setLevel(1) \
    ) \
    .addComponent(componentObject() \
     .setName("NURBS") \
     .setLevel(2) \
    ) \
    .addComponent(componentObject() \
     .setName("Core") \
     .setLevel(2) \
    ) \
    .addComponent(componentObject() \
     .setName("Navigation") \
     .setLevel(1) \
    ) \
    .addComponent(componentObject() \
     .setName("Text") \
     .setLevel(1) \
    ) \
    .addMeta(metaObject() \
     .setName("title") \
     .setContent("X3dHeaderPrototypeSyntaxExamples.x3d") \
    ) \
    .addMeta(metaObject() \
     .setName("description") \
     .setContent("X3D scene header and prototype syntax examples. This example header indicates that the content is XML encoded, follows the Interactive Profile and explicitly lists additional necessary components. The X3D header may also contain additional semantic information. Used for specification EXAMPLE excerpts in 19776:1 XML Encoding.") \
    ) \
    .addMeta(metaObject() \
     .setName("created") \
     .setContent("14 October 2002") \
    ) \
    .addMeta(metaObject() \
     .setName("modified") \
     .setContent("7 May 2017") \
    ) \
    .addMeta(metaObject() \
     .setName("creator") \
     .setContent("Don Brutzman") \
    ) \
    .addMeta(metaObject() \
     .setName("specificationSection") \
     .setContent("X3D encodings, ISO/IEC 19776-1.3, Part 1: XML encoding, 4.3 XML file syntax") \
    ) \
    .addMeta(metaObject() \
     .setName("specificationUrl") \
     .setContent("http://www.web3d.org/documents/specifications/19776-1/V3.3/Part01/concepts.html#XMLFileSyntax") \
    ) \
    .addMeta(metaObject() \
     .setName("identifier") \
     .setContent("http://www.web3d.org/x3d/content/examples/Basic/X3dSpecifications/X3dHeaderPrototypeSyntaxExamples.x3d") \
    ) \
    .addMeta(metaObject() \
     .setName("generator") \
     .setContent("X3D-Edit 3.3, https://savage.nps.edu/X3D-Edit") \
    ) \
    .addMeta(metaObject() \
     .setName("license") \
     .setContent("../license.html") \
    ) \
   ) \
   .setScene(SceneObject() \
    .addChild(ExternProtoDeclareObject() \
     .setName("ViewPositionOrientation") \
     .setUrl(["../../Savage/Tools/Authoring/ViewPositionOrientationPrototype.x3d#ViewPositionOrientation","https://savage.nps.edu/Savage/Tools/Authoring/ViewPositionOrientationPrototype.x3d#ViewPositionOrientation","../../Savage/Tools/Authoring/ViewPositionOrientationPrototype.wrl#ViewPositionOrientation","https://savage.nps.edu/Savage/Tools/Authoring/ViewPositionOrientationPrototype.wrl#ViewPositionOrientation"]) \
     .addField(fieldObject() \
      .setType(fieldObject.TYPE_SFBOOL) \
      .setName("enabled") \
      .setAccessType(fieldObject.ACCESSTYPE_INPUTOUTPUT) \
     ) \
     .addField(fieldObject() \
      .setType(fieldObject.TYPE_SFBOOL) \
      .setName("traceEnabled") \
      .setAccessType(fieldObject.ACCESSTYPE_INITIALIZEONLY) \
     ) \
     .addField(fieldObject() \
      .setType(fieldObject.TYPE_SFBOOL) \
      .setName("set_traceEnabled") \
      .setAccessType(fieldObject.ACCESSTYPE_INPUTONLY) \
     ) \
     .addField(fieldObject() \
      .setType(fieldObject.TYPE_SFVEC3F) \
      .setName("position_changed") \
      .setAccessType(fieldObject.ACCESSTYPE_OUTPUTONLY) \
     ) \
     .addField(fieldObject() \
      .setType(fieldObject.TYPE_SFROTATION) \
      .setName("orientation_changed") \
      .setAccessType(fieldObject.ACCESSTYPE_OUTPUTONLY) \
     ) \
     .addField(fieldObject() \
      .setType(fieldObject.TYPE_MFSTRING) \
      .setName("outputViewpointString") \
      .setAccessType(fieldObject.ACCESSTYPE_OUTPUTONLY) \
     ) \
    ) \
    .addChild(ProtoDeclareObject() \
     .setName("NewWorldInfoNode") \
     .setProtoBody(ProtoBodyObject() \
      .addChild(WorldInfoObject() \
       .setDEF("ExamplePrototypeBody") \
      ) \
     ) \
    ) \
    .addChild(ProtoInstanceObject() \
     .setName("NewWorldInfoNode") \
    ) \
    .addChild(ProtoDeclareObject() \
     .setName("EmissiveMaterial") \
     .setProtoInterface(ProtoInterfaceObject() \
      .addField(fieldObject() \
       .setType(fieldObject.TYPE_SFCOLOR) \
       .setName("onlyColor") \
       .setAccessType(fieldObject.ACCESSTYPE_INPUTOUTPUT) \
       .setValue("1 0 0") \
      ) \
     ) \
     .setProtoBody(ProtoBodyObject() \
      .addComments(CommentsBlock("""Override default diffuseColor value 0.8 0.8 0.8""")) \
      .addChild(MaterialObject() \
       .setDiffuseColor([0,0,0]) \
       .addComments(CommentsBlock("""Connect emissiveColor field of current node to onlyColor field of parent ProtoDeclare.""")) \
       .setIS(ISObject() \
        .addConnect(connectObject() \
         .setNodeField("emissiveColor") \
         .setProtoField("onlyColor") \
        ) \
       ) \
      ) \
     ) \
    ) \
    .addChild(ProtoDeclareObject() \
     .setName("ShiftGroupUp2m") \
     .setProtoInterface(ProtoInterfaceObject() \
      .addField(fieldObject() \
       .setType(fieldObject.TYPE_MFNODE) \
       .setName("children") \
       .setAccessType(fieldObject.ACCESSTYPE_INPUTOUTPUT) \
       .addChild(GroupObject() \
        .setDEF("DefaultNodeValue") \
        .setBboxSize([2,2,2]) \
        .addComments(CommentsBlock("""Authors need to override this node when creating the ProtoInstance fieldValue name=\"children\"""")) \
       ) \
      ) \
     ) \
     .setProtoBody(ProtoBodyObject() \
      .addChild(TransformObject() \
       .setTranslation([0,2,0]) \
       .addChild(GroupObject() \
        .setIS(ISObject() \
         .addConnect(connectObject() \
          .setNodeField("children") \
          .setProtoField("children") \
         ) \
        ) \
       ) \
      ) \
     ) \
    ) \
    .addChild(ProtoInstanceObject() \
     .setName("ShiftGroupUp2m") \
    ) \
    .addComments(CommentsBlock("""====================""")) \
    .addChild(ViewpointObject() \
     .setDEF("ExampleSingleElement") \
     .setDescription("Hello syntax") \
    ) \
    .addChild(GroupObject() \
     .setDEF("ExampleChildElement") \
     .addChild(ShapeObject() \
      .setGeometry(BoxObject() \
      ) \
      .setAppearance(AppearanceObject() \
       .setMaterial(MaterialObject() \
        .setDiffuseColor([0.6,0.4,0.2]) \
       ) \
      ) \
     ) \
    ) \
    .addChild(TransformObject() \
     .setDEF("TransformExampleUSE") \
     .setRotation([0,1,0,0.78]) \
     .setTranslation([0,2.5,0]) \
     .addChild(GroupObject() \
      .setUSE("ExampleChildElement") \
     ) \
    ) \
    .addChild(CollisionObject() \
     .setProxy(ShapeObject() \
      .addComments(CommentsBlock("""note that Collision proxy Shape is not rendered""")) \
      .addComments(CommentsBlock("""alternative: Text string='\"He said, \\&quot;Immel did it!\\&quot;\"'""")) \
      .setGeometry(TextObject() \
       .setString(["He said, \"Immel did it!\""]) \
      ) \
      .setAppearance(AppearanceObject() \
       .setMaterial(MaterialObject() \
       ) \
      ) \
     ) \
     .addChild(GroupObject() \
      .setUSE("ExampleChildElement") \
     ) \
    ) \
    .addChild(TransformObject() \
     .setTranslation([0,-2.5,0]) \
     .addChild(ShapeObject() \
      .setAppearance(AppearanceObject() \
       .setMaterial(ProtoInstanceObject() \
        .setName("EmissiveMaterial") \
        .addFieldValue(fieldValueObject() \
         .setName("onlyColor") \
         .setValue("0.2 0.6 0.6") \
        ) \
       ) \
      ) \
      .setGeometry(TextObject() \
       .setString(["X3D Header Prototype syntax examples","(view console for EXTERNPROTO output)"]) \
       .setFontStyle(FontStyleObject() \
        .setJustify(["MIDDLE","MIDDLE"]) \
        .setSize(0.6) \
       ) \
      ) \
     ) \
    ) \
    .addChild(ProtoInstanceObject() \
     .setName("ViewPositionOrientation") \
     .addFieldValue(fieldValueObject() \
      .setName("enabled") \
      .setValue("true") \
     ) \
    ) \
    .addChild(TimeSensorObject() \
     .setDEF("Clock") \
     .setCycleInterval(4) \
     .setLoop(True) \
    ) \
    .addChild(OrientationInterpolatorObject() \
     .setDEF("Spinner") \
     .setKey([0,0.5,1]) \
     .setKeyValue([0,1,0,0,0,1,0,3.14159,0,1,0,6.28318]) \
    ) \
    .addChild(ROUTEObject() \
     .setFromField("fraction_changed") \
     .setFromNode("Clock") \
     .setToField("set_fraction") \
     .setToNode("Spinner") \
    ) \
    .addChild(ROUTEObject() \
     .setFromField("value_changed") \
     .setFromNode("Spinner") \
     .setToField("rotation") \
     .setToNode("TransformExampleUSE") \
    ) \
    .addChild(InlineObject() \
     .setDEF("someInline") \
     .setUrl(["someUrl.x3d","http://www.web3d.org/x3d/content/examples/Basic/X3dSpecifications/someUrl.x3d"]) \
    ) \
    .addChild(IMPORTObject() \
     .setAS("someInlineRoot") \
     .setImportedDEF("someName") \
     .setInlineDEF("someInline") \
    ) \
    .addChild(PositionInterpolatorObject() \
     .setDEF("StayInPlace") \
     .setKey([0,1]) \
     .setKeyValue([0,0,0,0,0,0]) \
    ) \
    .addChild(ROUTEObject() \
     .setFromField("fraction_changed") \
     .setFromNode("Clock") \
     .setToField("set_fraction") \
     .setToNode("StayInPlace") \
    ) \
    .addChild(ROUTEObject() \
     .setFromField("value_changed") \
     .setFromNode("StayInPlace") \
     .setToField("set_translation") \
     .setToNode("someInlineRoot") \
    ) \
   ) \

X3D0.toFileX3D("./future/./X3dHeaderPrototypeSyntaxExamples.newf.x3d")
